name: mri_project
dependencies:
  - python=3.6
  - pip
  - pandas
  - ipykernel
  - jupyter
  - dask
  - distributed
  - scikit-learn
  - opencv
  - seaborn
  - tensorflow>=2.1

  - pip:
    - pathos
    - joblib
    - statsmodels
    - "--editable=."
